# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_utils_dataframes.ipynb (unless otherwise specified).

__all__ = ['join_df', 'display_all']

# Cell
from ..imports import *

# Cell
def join_df(left, right, left_on: list, right_on=None, suffix='_y', how='left'):
    """helper for pd.merge"""
    if right_on is None:
        right_on = left_on
    return left.merge(right, how=how, left_on=left_on, right_on=right_on, suffixes=("", suffix))


def display_all(df):
    """see more of the data frame"""
    with pd.option_context("display.max_rows", 1000):
        with pd.option_context("display.max_columns", 1000):
            display(df)