# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"FileHandling": "01_azure.ipynb",
         "unlink_files": "01_azure.ipynb",
         "ParseYaml": "02_utils_parseyaml.ipynb",
         "yml_reader": "02_utils_parseyaml.ipynb",
         "join_df": "03_utils_dataframes.ipynb",
         "display_all": "03_utils_dataframes.ipynb",
         "EncodeCats": "04_dstools_preparedata.ipynb",
         "FixMissing": "04_dstools_preparedata.ipynb",
         "Normalize": "04_dstools_preparedata.ipynb",
         "numericalize": "04_dstools_preparedata.ipynb",
         "split_data": "04_dstools_preparedata.ipynb",
         "SnowflakeTool": "05_snowflake_query.ipynb",
         "CopyInto": "06_snowflake_copyinto.ipynb"}

modules = ["azure/filehandling.py",
           "utils/parseyaml.py",
           "utils/dataframes.py",
           "dstools/preparedata.py",
           "snowflake/query.py",
           "snowflake/copyinto.py"]

doc_url = "https://celmore25.github.io/easymigration/"

git_url = "https://github.com/celmore25/easymigration/tree/main/"

def custom_doc_links(name): return None
