# Generated by Django 3.1.2 on 2020-12-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionality',
            name='form_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
